name: Test

on: [push]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        run: rustup update stable && rustup default stable
      - name: Run apt-get install pkg-config
        run: apt-get update && apt-get install pkg-config
      - name: Run cargo build
        run: cargo build