name: CI
on:
  push:
    branches-ignore: [master]
  pull_request:
    branches: ['*']
    
defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  rustfmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: rustup update stable && rustup default stable
    - run: rustup component add rustfmt
    - run: cargo fmt --all --check

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: rustup update stable && rustup default stable
    - run: cargo build

  success:
    permissions:
      contents: none
    name: bors build finished
    needs: [rustfmt, build]
    runs-on: ubuntu-latest
    if: "success() && github.event_name == 'push'"
    steps:
    - run: echo ok
  failure:
    permissions:
      contents: none
    name: bors build finished
    needs: [rustfmt, build]
    runs-on: ubuntu-latest
    if: "!success() && github.event_name == 'push'"
    steps:
    - run: exit 1